version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: pump-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass123
      - DOCKER_INFLUXDB_INIT_ORG=pump_org
      - DOCKER_INFLUXDB_INIT_BUCKET=pump_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=pump-agent-token-super-secret-123
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    networks:
      - pump-network
    restart: unless-stopped

  pump-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pump-agent
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=http://influxdb:8086
      - INFLUXDB_TOKEN=pump-agent-token-super-secret-123
      - INFLUXDB_DATABASE=pump_data
      - INFLUXDB_ORGANIZATION=pump_org
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    ports:
      - "3000:3000"
    networks:
      - pump-network
    restart: unless-stopped

volumes:
  influx_data:
    driver: local
  influx_config:
    driver: local

networks:
  pump-network:
    driver: bridge